name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deploy
      run: curl -X POST https://api.render.com/deploy/srv-d0qc56bipnbc73e8g2f0?key=5q9un_Yka0I
