name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check linting
      run:  ruff check .

  tests:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest test_app.py

    - name: Test with coverage
      run: |
        coverage run -m pytest
        coverage xml

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Slack notification for success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOKS_SLACK_URL }}
        SLACK_USERNAME: Test Bot
        SLACK_ICON_EMOJI: robot_face
        SLACK_CHANNEL: test
        SLACK_MESSAGE: 'Test successful!'
        SLACK_COLOR: success
        MSG_MINIMAL: Actions URL,Commit

    - name: Slack notification for failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOKS_SLACK_URL }}
        SLACK_USERNAME: Test Bot
        SLACK_ICON_EMOJI: robot_face
        SLACK_CHANNEL: test
        SLACK_MESSAGE: 'Test Failed!'
        SLACK_COLOR: failure
        MSG_MINIMAL: Actions URL,Commit

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
    - name: Deploy to Render
      uses: sws2apps/render-deployment@main
      with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
        multipleDeployment: false
    
    - name: Slack notification for success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOKS_SLACK_URL }}
        SLACK_USERNAME: Deploy Bot
        SLACK_ICON_EMOJI: robot_face
        SLACK_CHANNEL: deploy
        SLACK_MESSAGE: 'Deploy successful!'
        SLACK_COLOR: success
        MSG_MINIMAL: Actions URL,Commit

    - name: Slack notification for failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOKS_SLACK_URL }}
        SLACK_USERNAME: Deploy Bot
        SLACK_ICON_EMOJI: robot_face
        SLACK_CHANNEL: deploy
        SLACK_MESSAGE: 'Deploy Failed!'
        SLACK_COLOR: failure
        MSG_MINIMAL: Actions URL,Commit

  locust-test:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Locust Performance Tests
        uses: thomasvjoseph/locust@v1.1.7
        with:
          URL: https://iycs-ci.onrender.com/   # Replace with your target URL
          USERS: 2                       # Number of concurrent users
          RATE: 1                        # Rate of user spawning
          RUNTIME: 10s                   # Duration of the test
          HEADLESS: true                 # Run Locust in headless mode
          LOGLEVEL: DEBUG                # Set logging level
          html_report: 'example.html'    # Name of the HTML report file

      - name: Upload Locust Test Results
        uses: actions/upload-artifact@v4
        with:
          name: locust-report            # Name of the artifact
          path: example.html             # Path to the generated HTML report
          if-no-files-found: warn        # Warn if no files are found
          retention-days: 1              # Retention period for the artifact